galaxy_info:
  author: Mike Keller
  description: monero-node

  license: license (MIT)

  min_ansible_version: 2.4

  platforms:
   - name: Ubuntu
     versions:
     - xenial

  galaxy_tags: ['monero']
